version: '3.3'

services:
  mongo:
    image: mongo:6.0.1
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=accounts
    restart: always
    ports:
      - '27017-27019:27017-27019'